# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Updated GH Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm ci
        
    - run: npm run build --if-present
    - run: mkdir .ghpages
    - run: cp -r index.html assets build vendor CNAME .ghpages

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .ghpages
